spring:
  application:
    name: hiregami-api-gateway

  docker:
    compose:
      enabled: false
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    allow-redirects: true

  instance:
    prefer-ip-address: true
    instance-id: gateway-service
